### ISSUE TITLE
**Popular dados**

### ISSUE THREAD

**Issue by NatSatie** [NatSatie/letscode-projeto2#10]
Ver issue #8 

Fazer uma amostra de criação de uma disciplina e algumas perguntas de exemplo.

- [x] inser de um professor
- [x] insert de uma disciplina
- [x] insert de perguntas

Referências:

- W3 School
- Q concursos

**Comment by Carol195** [comment]
Concluido mas foi comitado na Branch #15 implementação do CRUD
